import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'
import AuthProvider from '@/components/AuthProvider'



const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}
const myFont = localFont({ src: './../fonts/NotoSerifBengali-VariableFont_wdth,wght.ttf' })
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

return(<html lang="en"><body className={myFont.className}><AuthProvider> {children}</AuthProvider></body></html>)
}
