import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'
import AuthProvider from '@/components/AuthProvider'
import Head from 'next/head'



const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
  verification:{
    google: 'gsNc4Ka7Bv99vMH3l-zk6X5GkvImBA-n0eUbI5g0OJI',
  }



}
const myFont = localFont({ src: './../fonts/NotoSerifBengali-VariableFont_wdth,wght.ttf' })
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

return(<html lang="en"><body className={myFont.className}>
   <Head>
        {/* Other meta tags or head elements */}
        <meta name="google-site-verification" content="gsNc4Ka7Bv99vMH3l-zk6X5GkvImBA-n0eUbI5g0OJI" />

        {/* Other meta tags or head elements */}
      </Head>
  <AuthProvider> {children}</AuthProvider></body></html>)
}
